package lostankit7.droid.moodtracker.utils.constant

import android.content.Context
import lostankit7.droid.moodtracker.R
import lostankit7.droid.moodtracker.data.database.entities.*

object SplashFragmentDataProvider {

    fun moodIcons(context: Context) = listOf(
        lostankit7.android.entry_data.database.entities.MoodIcon(MOOD_ICON_HAPPY,
            context.resources.getString(R.string.happy)),
        lostankit7.android.entry_data.database.entities.MoodIcon(MOOD_ICON_JOLLY,
            context.resources.getString(R.string.jolly)),
        lostankit7.android.entry_data.database.entities.MoodIcon(MOOD_ICON_MEH,
            context.resources.getString(R.string.meh)),
        lostankit7.android.entry_data.database.entities.MoodIcon(MOOD_ICON_SAD,
            context.resources.getString(R.string.sad)),
        lostankit7.android.entry_data.database.entities.MoodIcon(MOOD_ICON_AWFUL,
            context.resources.getString(R.string.awful)),
    )

    fun taskCategories(context: Context) = listOf(
        lostankit7.android.entry_data.database.entities.TaskCategory(context.resources.getString(R.string.work)),
        lostankit7.android.entry_data.database.entities.TaskCategory(context.resources.getString(R.string.entertainment)),
        lostankit7.android.entry_data.database.entities.TaskCategory(context.resources.getString(R.string.health)),
        lostankit7.android.entry_data.database.entities.TaskCategory(context.resources.getString(R.string.other))
    )

    fun taskIcons(context: Context): List<lostankit7.android.entry_data.database.entities.TaskIcon> = with(context.resources) {
        val list = mutableListOf<lostankit7.android.entry_data.database.entities.TaskIcon>()
        val cOther = getString(R.string.other)
        val cEntertainment = getString(R.string.entertainment)
        val cWork = getString(R.string.work)
        val cHealth = getString(R.string.health)


        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf4ce",
            getString(R.string.family),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf500",
            getString(R.string.friends),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf2e7",
            getString(R.string.food),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf1b9",
            getString(R.string.drive),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uF5DA",
            getString(R.string.books),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf564",
            getString(R.string.cookies),
            cOther))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf679",
            getString(R.string.pray),
            cOther))


        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf07a",
            getString(R.string.shopping),
            cEntertainment))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf008",
            getString(R.string.movies),
            cEntertainment))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf11b",
            getString(R.string.gaming),
            cEntertainment))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf79f",
            getString(R.string.party),
            cEntertainment))


        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf84a",
            getString(R.string.cycling),
            cHealth))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf70c",
            getString(R.string.sports),
            cHealth))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf44b",
            getString(R.string.gym),
            cHealth))


        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf5fc",
            getString(R.string.code),
            cWork))
        list.add(lostankit7.android.entry_data.database.entities.TaskIcon("\uf188",
            getString(R.string.bug),
            cWork))

        return list
    }

    fun suggestedMoodIcons() = listOf(
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5b8"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5b3"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5a4"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf59c"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf59a"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf598"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf58c"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf58b"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf589"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf588"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf587"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf586"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf585"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf584"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf583"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf582"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf581"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf580"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf57f"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf57a"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf579"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf556"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5a5"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5c8"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5c2"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf4da"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf5b4"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf596"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf58a"),
        lostankit7.android.entry_data.database.entities.SuggestedMoodIcon("\uf118"),
    )

    fun suggestedTaskIcons() = listOf(
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2BB", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF042", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF5D0",
            "freshener",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF461", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0F9",
            "ambulance",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2A3", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF13D", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF644", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2A2", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF559", "award", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF558", "web", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF77C", "baby", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF77D",
            "baby walk",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uE059",
            "bacteria",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF666", "boom", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF515",
            "balance",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF05E", "off", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF433",
            "baseball",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF434",
            "basketball",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2CD", "bath", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF244",
            "battery empty",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF240",
            "battery full",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF236", "bed", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0FC", "beer", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0F3", "bell", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1F6",
            "notification off",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF647", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF206",
            "bicycle",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF780", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1FD",
            "birthday",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF517", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0E7",
            "phone charging",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF781", "blog", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF5D7",
            "chicken",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1E2", "bomb", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF55C", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF518", "book", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF436",
            "bowling ball",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uE05B", "tissue", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF468", "puzzle", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF469",
            "first aid",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF519", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF51A", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF55D", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF55E", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF46A", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF140",
            "shooting",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0A1",
            "announcement",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1AD",
            "building",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF64A",
            "business",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF274",
            "meeting done",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF783",
            "meeting",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF273",
            "no meeting",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6BB", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF786", "hockey", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF55F", "flower", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF787", "carrot", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF51C",
            "teaching",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6C0", "chair", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF439", "chess", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF51D", "church", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF111",
            "blank dark",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF64F", "city", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1CE", "blank", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7F2",
            "medical",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0C2", "cloud", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF46D",
            "checklist",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF46C", "done", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF381",
            "cloud download",
            true),

        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF73C",
            "cloud,true rainy",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF73D", "rainy", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF740",
            "heavy rain",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF743",
            "cloud sunny rain",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6C4",
            "cloud sunny",
            true),

        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF561",
            "cocktail",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF121", "code", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF075", "coin", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0F4", "coffee", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF075",
            "message",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF563", "cookie", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF564",
            "cookie bite",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF4B8", "couch", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF564",
            "credit card",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF05B", "aim", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1C0",
            "database",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF655", "spider", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1B3", "cubes", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1B2", "cube", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0C4",
            "scissor",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF521", "crown", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF522", "dice", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6CF", "dice", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6D3", "dog", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF471", "", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF4BA", "bird", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF569", "drum", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6D5", "dragon", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF44B",
            "dumbell",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF658",
            "envelope",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF52D",
            "feather",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0FB", "flight", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF576", "fill", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF134",
            "fire extinguisher",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7E4", "fire", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF578", "fish", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF024", "flag", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF44E",
            "football",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF52F", "pump", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF79C", "gift", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF79C", "cheers", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6E3", "hammer", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7A6", "guitar", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF4C1", "hand", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF4C0", "hand", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF8C1", "hat", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF6EC", "hiking", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0F8",
            "hospital",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF593", "tub", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF593", "hotdog", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF06C", "leaf", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF094", "lemon", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0EB", "bulb", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF21C", "bike", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF1FC", "paint", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF0C6",
            "paperclip",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF5AB",
            "passport",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF4D3", "bank", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF818", "pizza", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF70C",
            "running",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF07A",
            "shopping",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF290",
            "shopping",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2CC", "shower", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7C5",
            "staking",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7CA", "skiing", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF48D", "smoke", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7D0",
            "snowman",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF48E",
            "syringe",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF769",
            "thermometer",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF76B",
            "thermometer",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2C7",
            "thermometer",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF491",
            "thermometer",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF2C8",
            "thermometer",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF164", "thumbs", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF165", "thumbs", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF722",
            "tractor",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF637",
            "traffic",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF7D9", "tools", true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF552",
            "toolbox",
            true),
        lostankit7.android.entry_data.database.entities.SuggestedTaskIcon("\uF238", "train", true)
    )

    fun suggestedMoodNames(context: Context): List<lostankit7.android.entry_data.database.entities.SuggestedMoodName> {
        val suggNames = context.resources.getStringArray(R.array.suggested_mood_names)
       return suggNames.map { lostankit7.android.entry_data.database.entities.SuggestedMoodName(it) }
    }

    fun suggestedTaskNames(context: Context) : List<lostankit7.android.entry_data.database.entities.SuggestedTaskName> {
        val suggNames = context.resources.getStringArray(R.array.suggested_task_names)
        return suggNames.map { lostankit7.android.entry_data.database.entities.SuggestedTaskName(it) }
    }

    private const val MOOD_ICON_HAPPY = "\uf599"
    private const val MOOD_ICON_SAD = "\uf119"
    private const val MOOD_ICON_MEH = "\uf11a"
    private const val MOOD_ICON_AWFUL = "\uf567"
    private const val MOOD_ICON_JOLLY = "\uf59b"
}